In [ ]:
import pandas as pd 
!wget -O titanic.csv https://www.dropbox.com/s/jhptjzvw6hq2sfv/titanic.csv?dl=0
titanic = pd.read_csv('titanic.csv')
titanic.head()

In [1]:
!wget -O titanic.csv https://www.dropbox.com/s/jhptjzvw6hq2sfv/titanic.csv?dl=0

--2021-05-23 03:39:47--  https://www.dropbox.com/s/jhptjzvw6hq2sfv/titanic.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6016:18::a27d:112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/jhptjzvw6hq2sfv/titanic.csv [following]
--2021-05-23 03:39:47--  https://www.dropbox.com/s/raw/jhptjzvw6hq2sfv/titanic.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc6392c7d992e8600fe87c729db5.dl.dropboxusercontent.com/cd/0/inline/BPAExYt7dNQeAmv-Fv8BUl4JBuVd8WEmGs4mRHCG5y_PA6QrOimTDyU5lunu8HHbofcr4hHlv8TYa6hQxWKmKliuDwMZo_rcxOPv-j0WU6f_qgb345SyroVbQnWkqvQ8_3IX2eDYjKX3GTkvJBWaN3VK/file# [following]
--2021-05-23 03:39:48--  https://uc6392c7d992e8600fe87c729db5.dl.dropboxusercontent.com/cd/0/inline/BPAExYt7dNQeAmv-Fv8BUl4JBuVd8WEmGs4mRHCG5y_PA6QrOimTDyU5lunu8HHbofcr4hHlv8TYa6hQxWKmKliuDwMZo_rcxOPv-j0WU6f_qgb345SyroVbQnWkqvQ8_3IX2eDYjKX3GTkvJBWaN3VK/file
Resolving uc6392c7d992e8600fe87c729db5.dl.dropboxusercontent.com (uc6392c7d992e8600fe87c729db5.dl.dropboxusercontent.com)... 162.125.1.15, 2620:100:6016:15::a27d:10f
Connecting to uc6392c7d992e8600fe87c729db5.dl.dropboxusercontent.com (uc6392c7d992e8600fe87c729db5.dl.dropboxusercontent.com)|162.125.1.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 108285 (106K) [text/plain]
Saving to: ‘titanic.csv’

titanic.csv         100%[===================>] 105.75K  --.-KB/s    in 0.04s

2021-05-23 03:39:48 (2.47 MB/s) - ‘titanic.csv’ saved [108285/108285]

In [2]:
import pandas as pd

In [3]:
titanic = pd.read_csv('titanic.csv')

In [4]:
titanic.head()

   pclass  survived  ...   body                        home.dest
0     1.0       1.0  ...    NaN                     St Louis, MO
1     1.0       1.0  ...    NaN  Montreal, PQ / Chesterville, ON
2     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON
3     1.0       0.0  ...  135.0  Montreal, PQ / Chesterville, ON
4     1.0       0.0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]